clear variables
clc

%% Algunas constantes
offset_codo = atan2(144,50);
qlim2 = [-pi/2 pi/2] - offset_codo;

%% Construcción de Links
L(1) = RevoluteMDH(...
    'd',0,...
    'a',0,...
    'alpha',0);

L(2) = RevoluteMDH(...
    'd',0,...
    'a',0,...
    'alpha',-pi/2,...
    'qlim', qlim2);

L(3) = RevoluteMDH(...
    'd',0,...
    'a',sqrt(50^2+144^2),...
    'alpha',0);

L(4) = RevoluteMDH(...
    'd',0,...
    'a',144,...
    'alpha',0);

L(5) = RevoluteMDH(...
    'd',144,...
    'a',0,...
    'alpha',pi/2);

Tool = transl([0 0 200]);
qz = [0 -offset_codo pi/2 pi/2 0];
%% Construcción del robot
robot = SerialLink(L,'tool', Tool);
robot.name = "WidowX Mark II";

robot.teach(qz);